# Generated by Django 6.0.5 on 2026-05-31 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the survey displayed to users.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='The question text displayed to users.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of questions within the survey.')),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice')], default='single_choice', help_text='single_choice: user selects one option; multiple_choice: user selects one or more options.', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(help_text='The survey this question belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dj_surveys.survey')),
            ],
            options={
                'ordering': ['survey', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyChoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(help_text="The choice text displayed to users (e.g., 'Build Tailwind integration').", max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of choices within the question.')),
                ('is_decline_option', models.BooleanField(default=False, help_text="If true, this choice represents 'I prefer not to answer' or 'Decline'. Used for banner dismissal and question opt-outs.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(help_text='The question this choice belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='dj_surveys.surveyquestion')),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyVote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(help_text='The choice selected by the user.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='dj_surveys.surveychoice')),
                ('question', models.ForeignKey(blank=True, help_text='The question being voted on. Denormalized for efficient querying.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='dj_surveys.surveyquestion')),
                ('survey', models.ForeignKey(help_text='The survey being voted on.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='dj_surveys.survey')),
                ('user', models.ForeignKey(help_text='The user who cast this vote.', on_delete=django.db.models.deletion.CASCADE, related_name='survey_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-voted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='surveychoice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_decline_option', True)), fields=('question',), name='one_decline_choice_per_question'),
        ),
        migrations.AddConstraint(
            model_name='surveychoice',
            constraint=models.CheckConstraint(condition=models.Q(('text', ''), _negated=True), name='choice_text_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='surveyvote',
            constraint=models.UniqueConstraint(fields=('user', 'choice'), name='one_vote_per_user_per_choice'),
        ),
    ]
