# Generated by Django 5.0.1 on 2024-02-07 17:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("dj_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
