# Generated by Django 5.0.6 on 2024-05-26 18:37

from django.db import migrations

import dj_users.models


class Migration(migrations.Migration):
    dependencies = [
        ("dj_users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", dj_users.models.UserManager()),
            ],
        ),
    ]
