"""Django settings for djforge project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import sys
from pathlib import Path

import environ

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file, if present
environ.Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-e**-$_v&pmln#j*$_$_$nljc!+hxlhlxla3_l5f*4qbdw5s0%n"

# False if not in os.environ because of casting above
DEBUG = env("DEBUG")

#
# Allow from everywhere if DEBUG is True as in many cases the application will run
# in a containerized environment which will take care of shielding host access.
#
ALLOWED_HOSTS = [] if DEBUG else ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "compressor",
    "dj_theme",
    "dj_favicons",
    "dj_landing_page",
    # Content app to host some static content that the site might need.
    # There are some Django CMS packages with proper editors, decided to
    # use this as a first "simple" option, and perhaps integrate a CMS
    # later on.
    "dj_content",
    # Has one form to capture email address and handles so that people
    # can register interest in the project. Can be used to capture initial attention
    # for experiments to see if there is enough momentum to pursue.
    "dj_register_interest",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

#
# Conditionally add livereload to the mix if DEBUG is True
#
if DEBUG:
    INSTALLED_APPS.append("livereload")
    MIDDLEWARE.append("livereload.middleware.LiveReloadScript")


ROOT_URLCONF = "djforge.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "djforge.wsgi.application"

#
#  ___       _        _
# |   \ __ _| |_ __ _| |__  __ _ ___ ___
# | |) / _` |  _/ _` | '_ \/ _` (_-</ -_)
# |___/\__,_|\__\__,_|_.__/\__,_/__/\___|
#
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
#
# Used default database configuration from docker-compose.yml if DATABASE_URL is not set
#
postgres_config_common = {
    "ENGINE": "django.db.backends.postgresql",
    "CONN_HEALTH_CHECKS": True,
    "ATOMIC_REQUESTS": True,
}

if env.str("DATABASE_URL", ""):
    # print("Using DATABASE_URL")
    default_database = env.db() | postgres_config_common
else:
    # Defaults aligned with docker-compose.yml
    default_database = {
        "HOST": "localhost",
        "USER": "dj_forge_user",
        "NAME": "dj_forge_main_database",
        "PASSWORD": "dj_forge_password",
        "PORT": 5432,
    } | postgres_config_common

DATABASES = {"default": default_database}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#   ____
#  / ___|___  _ __ ___  _ __  _ __ ___  ___ ___  ___  _ __
# | |   / _ \| '_ ` _ \| '_ \| '__/ _ \/ __/ __|/ _ \| '__|
# | |__| (_) | | | | | | |_) | | |  __/\__ \__ \ (_) | |
#  \____\___/|_| |_| |_| .__/|_|  \___||___/___/\___/|_|
#                      |_|
#
# Compressor Configuration
#
COMPRESS_ROOT = BASE_DIR / "static"

COMPRESS_ENABLED = True

#
# First two are the defaults, then added compressor
#
STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
)

#  _                      _
# | |    ___   __ _  __ _(_)_ __   __ _
# | |   / _ \ / _` |/ _` | | '_ \ / _` |
# | |__| (_) | (_| | (_| | | | | | (_| |
# |_____\___/ \__, |\__, |_|_| |_|\__, |
#             |___/ |___/         |___/
#
# Log to console in DEBUG mode
# Reference:
# - https://odwyer.software/blog/logging-to-standard-output-with-django
#
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "%(asctime)s %(name)-12s %(levelname)-8s %(message)s"},
        "simple": {
            "format": "{name} at {asctime} ({levelname}) :: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "verbose",
        }
    },
    "loggers": {
        # Too Verbose:
        # "django": {
        #     "handlers": ["console"],
        #     "level": "DEBUG",
        #     "propagate": True,
        # },
        "": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}
