"""Django settings for djforge project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import environ

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    ENVIRONMENT=(str, "production"),  # Be as alert as possible if not set
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file, if present
environ.Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# A secret key is required for production, supplying a default for development
# and testing purposes.
# Generate one with:
# make secret_key
SECRET_KEY = env.str(
    "SECRET_KEY", "django-8hzm)&2gdw2f7i$be!worf!9r9(0a@*7um*q*uwoyb_#y!*5j"
)
# False if not in os.environ because of casting above
DEBUG = env("DEBUG")

# Set the current environment:
ENVIRONMENT = env("ENVIRONMENT")

#
# Allow from everywhere if DEBUG is True as in many cases the application will run
# in a containerized environment which will take care of shielding host access.
#
ALLOWED_HOSTS = [] if DEBUG else ["*"]

#
# Define parameter in order to use allauth:
#
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_results",
    "django_extensions",
    "dj_theme",
    "dj_favicons",
    #
    # User Management App which contains the user model defined in AUTH_USER_MODEL
    #
    "dj_users",
    "dj_landing_page",
    # Content app to host some static content that the site might need.
    # There are some Django CMS packages with proper editors, decided to
    # use this as a first "simple" option, and perhaps integrate a CMS
    # later on.
    "dj_content",
    #
    # Single point of contact for all email dispatching. Templates are to be stored
    # in the dj_emails app, and the dispatching is done from here.
    #
    "dj_emails",
    # Dashboard as a login destination page always has lots of functionality hence
    # deciding it to "live" in its own app.
    "dj_dashboard",
    #
    # Asynchronous tasks, aiming to have some for testing and health checks purposes,
    # plus later on a central location for cron related triggers.
    #
    "dj_tasks",
    #
    # Contact Us app, to have a simple form for people to communicate with the project.
    # Different than registering interest, as this is more for general inquiries plus
    # it is supposed to be part of the application "for ever", while registering
    # interest should be removed once the project is "live".
    #
    "dj_contact_us",
    # Has one form to capture email address and handles so that people
    # can register interest in the project. Can be used to capture initial attention
    # for experiments to see if there is enough momentum to pursue.
    "dj_register_interest",
    #
    # Proof of Concepts app, to test out various things, and to have a place to
    # experiment with new ideas, discuss mocks, or display what the project can do.
    #
    "dj_pocs",
    #
    # Allauth items, having only base and account for local storage of user credentials
    # (mainly email and password), others can be added here such as Google, Facebook,
    # etc.
    #
    # Needs to be placed after "dj_users" so that templates "forked"
    # there can be overridden.
    "allauth",
    "allauth.account",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Add Allauth's middleware:
    "allauth.account.middleware.AccountMiddleware",
]

#
# Conditionally add livereload to the mix if DEBUG is True
#
if DEBUG:
    INSTALLED_APPS.append("livereload")
    MIDDLEWARE.append("livereload.middleware.LiveReloadScript")
else:
    securityMiddlewarePosition = MIDDLEWARE.index(
        "django.middleware.security.SecurityMiddleware"
    )
    MIDDLEWARE.insert(
        securityMiddlewarePosition + 1, "whitenoise.middleware.WhiteNoiseMiddleware"
    )

ROOT_URLCONF = "djforge.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "djforge.wsgi.application"

#
#  ___       _        _
# |   \ __ _| |_ __ _| |__  __ _ ___ ___
# | |) / _` |  _/ _` | '_ \/ _` (_-</ -_)
# |___/\__,_|\__\__,_|_.__/\__,_/__/\___|
#
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
#
# Used default database configuration from docker-compose.yml if DATABASE_URL is not set
#
postgres_config_common = {
    "ENGINE": "django.db.backends.postgresql",
    "CONN_HEALTH_CHECKS": True,
    "ATOMIC_REQUESTS": True,
}

if env.str("DATABASE_URL", ""):
    # print("Using DATABASE_URL")
    default_database = env.db() | postgres_config_common
else:
    # Defaults aligned with docker-compose.yml
    default_database = {
        "HOST": "localhost",
        "USER": "dj_forge_user",
        "NAME": "dj_forge_main_database",
        "PASSWORD": "dj_forge_password",
        "PORT": 5432,
    } | postgres_config_common

DATABASES = {"default": default_database}

#   ___     _
#  / __|___| |___ _ _ _  _
# | (__/ -_) / -_) '_| || |
#  \___\___|_\___|_|  \_, |
#                     |__/
#
# Asynchronous tasks configuration
#
CELERY_RESULT_BACKEND = "django-db"
CELERY_BROKER_URL = env.str(
    "CELERY_BROKER_URL",  # Use first CELERY_BROKER_URL
    env.str(
        "REDIS_URL",  # ... then a REDIS_URL for Redis if it is set
        "redis://:dj_forge_redis_password@localhost:6379/0",  # finally a dev default
    ),
)

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# https://docs.render.com/deploy-django
# This production code might break development mode,
# so we check whether we're in DEBUG mode:
if not DEBUG:
    # Tell Django to copy static assets into a path called
    # `staticfiles` (this is specific to Render)
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
    # Enable the WhiteNoise storage backend,
    # which compresses static files to reduce disk use and renames the files with
    # unique names for each version to support long-term caching
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#  _                      _
# | |    ___   __ _  __ _(_)_ __   __ _
# | |   / _ \ / _` |/ _` | | '_ \ / _` |
# | |__| (_) | (_| | (_| | | | | | (_| |
# |_____\___/ \__, |\__, |_|_| |_|\__, |
#             |___/ |___/         |___/
#
# Log to console in DEBUG mode
# Reference:
# - https://odwyer.software/blog/logging-to-standard-output-with-django
#
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "%(asctime)s %(name)-12s %(levelname)-8s %(message)s"},
        "simple": {
            "format": "{name} at {asctime} ({levelname}) :: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "verbose",
        }
    },
    "loggers": {
        # Too Verbose:
        # "django": {
        #     "handlers": ["console"],
        #     "level": "DEBUG",
        #     "propagate": True,
        # },
        "": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

#  ___            _ _    ___           __ _                    _   _
# | __|_ __  __ _(_) |  / __|___ _ _  / _(_)__ _ _  _ _ _ __ _| |_(_)___ _ _
# | _|| '  \/ _` | | | | (__/ _ \ ' \|  _| / _` | || | '_/ _` |  _| / _ \ ' \
# |___|_|_|_\__,_|_|_|  \___\___/_||_|_| |_\__, |\_,_|_| \__,_|\__|_\___/_||_|
#                                          |___/
#
# Email configuration
#
# Defaults for development, need to extend for production
#
if ENVIRONMENT == "development":
    # Use Mailcrab documented in docker-compose.yml:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_PORT = env.int("EMAIL_PORT", 1025)

#    _       _   _
#   /_\ _  _| |_| |_
#  / _ \ || |  _| ' \
# /_/ \_\_,_|\__|_||_|
#
# Authentication related configuration
#
AUTH_USER_MODEL = "dj_users.User"
LOGIN_REDIRECT_URL = "/dashboard"

#    _   _ _   _       _   _
#   /_\ | | | /_\ _  _| |_| |_
#  / _ \| | |/ _ \ || |  _| ' \
# /_/ \_\_|_/_/ \_\_,_|\__|_||_|
#
# Allauth Configuration
#
# Reference: https://docs.allauth.org/en/latest/account/configuration.html
#
ACCOUNT_EMAIL_REQUIRED = True  # Email is used instead of username
if ENVIRONMENT == "development":
    ACCOUNT_EMAIL_VERIFICATION = "optional"
else:  # Any form of email sending not implemented
    ACCOUNT_EMAIL_VERIFICATION = "none"

ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_USERNAME_REQUIRED = False

if DEBUG:
    # Something for debug nothing for production.
    # Helps in case settings "slip": "What is this prefix in the emails?"
    ACCOUNT_EMAIL_SUBJECT_PREFIX = "[djforge] "
else:
    ACCOUNT_EMAIL_SUBJECT_PREFIX = ""

#
# The URL (or URL name) to redirect to directly after signing up.
# Note that users are only redirected to this URL if the signup went
# through uninterruptedly, ...
#
# Uncomment/Remove if you want to be the same as LOGIN_REDIRECT_URL
#
ACCOUNT_SIGNUP_REDIRECT_URL = "/dashboard/signup"

#    _   ___ ___   _  __
#   /_\ | _ \_ _| | |/ /___ _  _ ___
#  / _ \|  _/| |  | ' </ -_) || (_-<
# /_/ \_\_| |___| |_|\_\___|\_, /__/
#                           |__/
#
# Different API Keys used throughout the project
GOOGLE_MAPS_API_KEY = env.str("GOOGLE_MAPS_API_KEY", "")  # No default
