databases:
  - name: djforgedb
    plan: free
    databaseName: djforge_database
    user: djforge_user

services:
  - type: web
    plan: free
    name: djforge
    runtime: python
    buildCommand: "make build"
    startCommand: "python -m gunicorn djforge.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: djforgedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
