# Generated by Django 5.2.1 on 2025-08-05 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "stripe_product_id",
                    models.CharField(
                        help_text="The product ID from Stripe (e.g., prod_ABC123)",
                        max_length=255,
                        unique=True,
                        verbose_name="Stripe Product ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which this plan appears on the pricing page (lower numbers first)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this plan is currently available for purchase",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Plans",
                "db_table": "dj_billing_plan",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "stripe_customer_id",
                    models.CharField(
                        help_text="The customer ID from Stripe",
                        max_length=255,
                        unique=True,
                        verbose_name="Stripe Customer ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "dj_billing_customer",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        help_text="The subscription ID from Stripe",
                        max_length=255,
                        unique=True,
                        verbose_name="Stripe Subscription ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("incomplete", "Incomplete"),
                            ("incomplete_expired", "Incomplete Expired"),
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("unpaid", "Unpaid"),
                            ("paused", "Paused"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(
                        help_text="Start of the current billing period",
                        verbose_name="Current Period Start",
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        help_text="End of the current billing period",
                        verbose_name="Current Period End",
                    ),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the subscription will be canceled at period end",
                        verbose_name="Cancel at Period End",
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the subscription was canceled",
                        null=True,
                        verbose_name="Canceled At",
                    ),
                ),
                (
                    "trial_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of the trial period",
                        null=True,
                        verbose_name="Trial Start",
                    ),
                ),
                (
                    "trial_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End of the trial period",
                        null=True,
                        verbose_name="Trial End",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="dj_billing.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="dj_billing.plan",
                        verbose_name="Plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "db_table": "dj_billing_subscription",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        help_text="The payment intent ID from Stripe",
                        max_length=255,
                        unique=True,
                        verbose_name="Stripe Payment Intent ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount in USD",
                        max_digits=10,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="usd", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requires_payment_method", "Requires Payment Method"),
                            ("requires_confirmation", "Requires Confirmation"),
                            ("requires_action", "Requires Action"),
                            ("processing", "Processing"),
                            ("requires_capture", "Requires Capture"),
                            ("canceled", "Canceled"),
                            ("succeeded", "Succeeded"),
                        ],
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Payment description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="dj_billing.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="dj_billing.subscription",
                        verbose_name="Subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "dj_billing_payment",
                "ordering": ["-created_at"],
            },
        ),
    ]
