# Generated by Django 5.2.1 on 2025-08-06 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dj_billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["stripe_customer_id"], name="dj_billing__stripe__e5f94c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["stripe_payment_intent_id"],
                name="dj_billing__stripe__67599e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="dj_billing__status_4989fe_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["customer", "status"], name="dj_billing__custome_f0d145_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["-created_at"], name="dj_billing__created_42e128_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["stripe_subscription_id"], name="dj_billing__stripe__5f62cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="dj_billing__status_18a27d_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["customer", "status"], name="dj_billing__custome_2ebac2_idx"
            ),
        ),
    ]
