# Generated by Django 5.0.2 on 2024-03-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dj_register_interest", "0002_interest_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="interest",
            name="user_intent",
            field=models.TextField(
                default=".",
                verbose_name="Please write a short description of what do you hope to achieve with our solution?",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="interest",
            name="github_handle",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="(Optional) Github Handle in case solutions grants access a repository",
            ),
        ),
    ]
