# Generated by Django 5.0.2 on 2024-03-13 21:50

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "dj_register_interest",
            "0003_interest_user_intent_alter_interest_github_handle",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interest",
            name="created_at",
        ),
        migrations.AddField(
            model_name="interest",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
