#!/usr/bin/env bash
#
# Reference:
#
# https://ryan.himmelwright.net/post/scripting-tmux-workspaces/
#

#
# Exit if tmux is not installed
#
if ! command -v tmux &> /dev/null
then
  echo "tmux could not be found"
  exit 1
fi

# Set Session Name
SESSION="Water_Direct_Main_App"

# Check if session exists
SESSION_EXISTS=$(tmux list-sessions 2>/dev/null | grep "^${SESSION}:" || true)

# Only create tmux session if it doesn't already exist
if [ -z "${SESSION_EXISTS}" ]; then
    # Start New Session with our name
    tmux new-session -d -s "$SESSION"

    # Create windows for different tasks
    tmux rename-window -t "${SESSION}:0" 'make-up'
    tmux new-window -t "${SESSION}" -n 'django'
    tmux new-window -t "${SESSION}" -n 'celery'
    tmux new-window -t "${SESSION}" -n 'livereload'
    tmux new-window -t "${SESSION}" -n 'extra'
    tmux new-window -t "${SESSION}" -n 'extra-1'
    tmux new-window -t "${SESSION}" -n 'extra-2'

    # Send commands to respective windows
    tmux send-keys -t "${SESSION}:make-up" 'echo "Window: make-up"' C-m
    tmux send-keys -t "${SESSION}:make-up" ' make up' C-m
    sleep 5

    tmux send-keys -t "${SESSION}:django" 'echo "Window: django"' C-m
    tmux send-keys -t "${SESSION}:django" ' make django_runserver' C-m

    tmux send-keys -t "${SESSION}:celery" 'echo "Window: celery"' C-m
    tmux send-keys -t "${SESSION}:celery" ' make celery_debug' C-m

    tmux send-keys -t "${SESSION}:livereload" 'echo "Window: Live Reload"' C-m
    tmux send-keys -t "${SESSION}:livereload" ' make livereload' C-m

    tmux send-keys -t "${SESSION}:extra" 'echo "Window: extra"' C-m

    # Select the first window
    # tmux select-window -t "${SESSION}:make-up"
    tmux select-window -t "${SESSION}:django"
fi

# Attach to the session
tmux attach-session -t "${SESSION}"
