# Generated by Django 5.0.3 on 2024-04-23 19:21

import django_extensions.db.fields

import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dj_contact_us", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactusentry",
            name="created_at",
        ),
        migrations.AddField(
            model_name="contactusentry",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
